# Generated by Django 5.2 on 2025-12-16 18:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role_management.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='content_types',
            field=models.ManyToManyField(related_name='modules', through='role_management.ModuleContentType', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'A group need to have at least one permission in the module'), django.core.validators.MaxValueValidator(15, 'Currently a group cannot have more than four permissions in the module')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='auth.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role_management.module')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'group'), name='unique_module_group')],
            },
        ),
        migrations.AddConstraint(
            model_name='modulecontenttype',
            constraint=models.UniqueConstraint(fields=('content_type',), name='unique_content_type_module'),
        ),
    ]
